name: Deploy Oaisbr-API Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: [self-hosted, Linux, x64, runner-persea]
    environment:
      name: test
      url: 'http://172.16.16.112:3000/'

    steps:
      - uses: actions/checkout@v3
      - run: |
          sh scripts/deploy.sh
  prod:
    runs-on: [self-hosted, Linux, x64, runner-peroba]
    environment:
      name: prod
      url: 'https://api-oasisbr.ibict.br/'

    steps:
      - uses: actions/checkout@v3
      - run: |
          sh scripts/deploy.sh
